name: Build PassLOCK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Clang 21
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-21 lld-21

      - name: Set Clang 21
        run: |
          echo "CC=clang-21" >> $GITHUB_ENV
          echo "CXX=clang++-21" >> $GITHUB_ENV

      - name: Build Geode mod
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: nightly
          target: MacOS

      - name: Upload Geode
        uses: actions/upload-artifact@v4
        with:
          name: PassLOCK
          path: "**/*.geode"
